name: Build

on:
  workflow_dispatch:

env:
  SOURCE_DATE_EPOCH: 1775932932
  ZERO_AR_DATE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build-win-mac:
    name: Build ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: win-x64
            os: windows-2025
            ext: .exe
          - rid: win-arm64
            os: windows-2025
            ext: .exe

          - rid: osx-x64
            os: macos-26-intel
            ext: ''
          - rid: osx-arm64
            os: macos-26
            ext: ''

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Publish DumbVersionCreator
        run: dotnet publish DumbVersionCreator/DumbVersionCreator.csproj -c Release -r ${{ matrix.rid }} -o ./output/Creator

      - name: Publish DumbVersionPatcher
        run: dotnet publish DumbVersionPatcher/DumbVersionPatcher.csproj -c Release -r ${{ matrix.rid }} -o ./output/Patcher

      - name: Upload DumbVersionCreator
        uses: actions/upload-artifact@v7
        with:
          name: DumbVersionCreator-${{ matrix.rid }}
          path: ./output/Creator/DumbVersionCreator${{ matrix.ext }}
          retention-days: 7
          if-no-files-found: error
          archive: false

      - name: Upload DumbVersionPatcher
        uses: actions/upload-artifact@v7
        with:
          name: DumbVersionPatcher-${{ matrix.rid }}
          path: ./output/Patcher/DumbVersionPatcher${{ matrix.ext }}
          retention-days: 7
          if-no-files-found: error
          archive: false

  build-linux:
    name: Build ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: linux-x64
            os: ubuntu-22.04
            # dotnet/sdk:10.0-aot
            image: mcr.microsoft.com/dotnet/sdk@sha256:2a3317f21190fe1b530e02a9d393e5016d709d78b7e523d1f0a0082b31e777fe
            ext: ''

          - rid: linux-arm64
            os: ubuntu-22.04-arm
            # dotnet/sdk:10.0-aot
            image: mcr.microsoft.com/dotnet/sdk@sha256:2a3317f21190fe1b530e02a9d393e5016d709d78b7e523d1f0a0082b31e777fe
            ext: ''

          - rid: linux-musl-x64
            os: ubuntu-22.04
            # dotnet/sdk:10.0-alpine-aot
            image: mcr.microsoft.com/dotnet/sdk@sha256:9efc18e1243d667f1412209d6b3242d6ebdf14e57294f7f9ed4aca0bbe44ab8a
            ext: ''

    container:
      image: ${{ matrix.image }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Publish DumbVersionCreator
        run: dotnet publish DumbVersionCreator/DumbVersionCreator.csproj -c Release -r ${{ matrix.rid }} -o ./output/Creator

      - name: Publish DumbVersionPatcher
        run: dotnet publish DumbVersionPatcher/DumbVersionPatcher.csproj -c Release -r ${{ matrix.rid }} -o ./output/Patcher

      - name: Upload DumbVersionCreator
        uses: actions/upload-artifact@v7
        with:
          name: DumbVersionCreator-${{ matrix.rid }}
          path: ./output/Creator/DumbVersionCreator${{ matrix.ext }}
          retention-days: 7
          if-no-files-found: error
          archive: false

      - name: Upload DumbVersionPatcher
        uses: actions/upload-artifact@v7
        with:
          name: DumbVersionPatcher-${{ matrix.rid }}
          path: ./output/Patcher/DumbVersionPatcher${{ matrix.ext }}
          retention-days: 7
          if-no-files-found: error
          archive: false
