name: Build

on:
  workflow_dispatch:

env:
  SOURCE_DATE_EPOCH: 1775932932
  ZERO_AR_DATE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build-win-mac:
    name: Build ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: win-x64
            os: windows-2025
          - rid: win-arm64
            os: windows-11-arm

          - rid: osx-x64
            os: macos-26-intel
          - rid: osx-arm64
            os: macos-26

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Publish DumbVersionCreator
        run: dotnet publish DumbVersionCreator/DumbVersionCreator.csproj -c Release -r ${{ matrix.rid }} -o ./output/Creator

      - name: Publish DumbVersionPatcher
        run: dotnet publish DumbVersionPatcher/DumbVersionPatcher.csproj -c Release -r ${{ matrix.rid }} -o ./output/Patcher

      - name: Stage Unix Binaries
        if: runner.os == 'macOS'
        run: |
          mkdir -p ./release
          cp ./output/Creator/DumbVersionCreator ./release/
          cp ./output/Patcher/DumbVersionPatcher ./release/

      - name: Stage Windows Binaries
        if: runner.os == 'Windows'
        run: |
          New-Item -ItemType Directory -Force -Path ./release/
          Copy-Item ./output/Creator/DumbVersionCreator.exe ./release/
          Copy-Item ./output/Patcher/DumbVersionPatcher.exe ./release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: DumbVersion-${{ matrix.rid }}
          path: ./release/*
          retention-days: 7

  build-linux:
    name: Build ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: linux-x64
            os: ubuntu-22.04
            # dotnet/sdk:10.0-aot
            image: mcr.microsoft.com/dotnet/sdk@sha256:2a3317f21190fe1b530e02a9d393e5016d709d78b7e523d1f0a0082b31e777fe

          - rid: linux-arm64
            os: ubuntu-22.04-arm
            # dotnet/sdk:10.0-aot
            image: mcr.microsoft.com/dotnet/sdk@sha256:2a3317f21190fe1b530e02a9d393e5016d709d78b7e523d1f0a0082b31e777fe

          - rid: linux-musl-x64
            os: ubuntu-22.04
            # dotnet/sdk:10.0-alpine-aot
            image: mcr.microsoft.com/dotnet/sdk@sha256:9efc18e1243d667f1412209d6b3242d6ebdf14e57294f7f9ed4aca0bbe44ab8a

    container:
      image: ${{ matrix.image }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Publish DumbVersionCreator
        run: dotnet publish DumbVersionCreator/DumbVersionCreator.csproj -c Release -r ${{ matrix.rid }} -o ./output/Creator

      - name: Publish DumbVersionPatcher
        run: dotnet publish DumbVersionPatcher/DumbVersionPatcher.csproj -c Release -r ${{ matrix.rid }} -o ./output/Patcher

      - name: Stage Linux Binaries
        run: |
          mkdir -p ./release
          cp ./output/Creator/DumbVersionCreator ./release/
          cp ./output/Patcher/DumbVersionPatcher ./release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: DumbVersion-${{ matrix.rid }}
          path: ./release/*
          retention-days: 7